# Generated by Django 5.1.4 on 2025-02-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
