# Generated by Django 5.1.4 on 2025-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_activity_image_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='location',
        ),
    ]
