# Generated by Django 5.1.4 on 2025-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_food_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
