# Generated by Django 5.1.4 on 2025-03-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_remove_activity_image_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='location.location'),
        ),
    ]
