# Generated by Django 5.1.4 on 2025-02-23 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.RemoveField(
            model_name='touristtip',
            name='location',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visited_locations',
            field=models.ManyToManyField(through='users.UserVisit', to='location.location'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='TouristTip',
        ),
    ]
