# Generated by Django 5.1.4 on 2025-03-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_venue_location_alter_uservisit_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservisit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uservisit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='uservisit',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visited_locations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_radius',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
        migrations.DeleteModel(
            name='SavedItem',
        ),
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
