services:
  - type: web
    name: wondersri-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT --proxy-headers WonderSri_backend.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: wondersri-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: "wondersri-backend-tracking.onrender.com" 

  - type: postgres
  name: wondersri-prod-db
  plan: starter
  databaseName: wondersri_main
  user: wondersri_django_prod_user