# Generated by Django 5.1.6 on 2025-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geojson', models.JSONField()),
                ('radius', models.FloatField(help_text='Radius in meters')),
            ],
        ),
    ]
