# Generated by Django 5.1.6 on 2025-03-08 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_maingeofence_subgeofence_delete_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgeofence',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
