# Generated by Django 5.1.6 on 2025-02-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_geofence_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='geofence',
            table=None,
        ),
    ]
