# Generated by Django 5.1.6 on 2025-03-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_maingeofence_center_subgeofence_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maingeofence',
            old_name='center',
            new_name='main_point',
        ),
        migrations.RenameField(
            model_name='subgeofence',
            old_name='center',
            new_name='main_point',
        ),
    ]
