# Generated by Django 5.1.6 on 2025-03-11 20:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_subgeofence_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maingeofence',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='subgeofence',
            name='radius',
        ),
        migrations.AlterField(
            model_name='maingeofence',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='subgeofence',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='subgeofence',
            name='main_geofence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_geofences', to='tracking.maingeofence'),
        ),
    ]
