# Generated by Django 5.1.6 on 2025-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_maingeofence_radius_remove_subgeofence_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingeofence',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgeofence',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
