# Generated by Django 5.1.6 on 2025-03-19 04:50

import django.contrib.gis.db.models.fields
from django.db import migrations

def forward(apps, schema_editor):
    # This is the custom SQL to cast the location column to geometry type.
    schema_editor.execute('ALTER TABLE tracking_maingeofence ALTER COLUMN location TYPE geometry(Polygon, 4326) USING location::geometry(Polygon, 4326);')
    schema_editor.execute('ALTER TABLE tracking_subgeofence ALTER COLUMN location TYPE geometry(Polygon, 4326) USING location::geometry(Polygon, 4326);')


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_maingeofence_image_url_subgeofence_image_url'),
    ]

    operations = [
        migrations.RunPython(forward), 
        migrations.AlterField(
            model_name='maingeofence',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='subgeofence',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
